name: check_minor_dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * 1' # 5:30 PM UTC every Monday, 2:30 PM Argentina
env:
  FORCE_COLOR: 3
defaults:
  run:
    shell: bash

# *************************   TRIGGERING FURTHER WORKFLOW RUNS ***************************
# https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

jobs:
  update_minor_dependencies:
    timeout-minutes: 2
    if: github.event.repository.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Check dependencies
        id: check_dependencies
        run: |
          output=$(npx npm-check-updates --deep --target minor --jsonUpgraded)
          num_properties=$(echo "$output" | jq '[.[] | length] | add')
          if [ "$num_properties" -gt 0 ]; then
            echo "The JSON contains properties."
          else
            echo "The JSON is not empty but has no properties."
          fi
          echo "num_properties=$num_properties" >> $GITHUB_OUTPUT
      - name: Update dependencies
        if: ${{ steps.check_dependencies.outputs.num_properties > 0 }}
        run: |
          npx npm-check-updates --deep --target minor -u
          pnpm install --no-frozen-lockfile && pnpm dedupe
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'dependencies: Upgrade NPM packages (automated)'
          branch: 'upgrade-npm-packages'
          commit-message: 'dependencies: Upgrade NPM packages (automated)'
          body: |
            ### ⚠ Importante leer antes de hacer merge a main
            >Cerrar esta **PR** y abrirla de nuevo para que corran las **actions**
            de **code-quality-check**.

            >Luego _merge_ a **main**.
